package mupi.com.mortgageproject.loan;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class solicitud implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("codigoProducto")
   private String codigoProducto;

   public solicitud()
   {
   }

   public java.lang.String getCodigoProducto()
   {
      return this.codigoProducto;
   }

   public void setCodigoProducto(java.lang.String codigoProducto)
   {
      this.codigoProducto = codigoProducto;
   }

   public solicitud(java.lang.String codigoProducto)
   {
      this.codigoProducto = codigoProducto;
   }

}