package mupi.com.mortgageproject.loan;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class solicitud implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "codigoProducto")
   private mupi.com.mortgageproject.loan.solicitud codigoProducto;

   public solicitud()
   {
   }

   public mupi.com.mortgageproject.loan.solicitud getCodigoProducto()
   {
      return this.codigoProducto;
   }

   public void setCodigoProducto(
         mupi.com.mortgageproject.loan.solicitud codigoProducto)
   {
      this.codigoProducto = codigoProducto;
   }

   public solicitud(mupi.com.mortgageproject.loan.solicitud codigoProducto)
   {
      this.codigoProducto = codigoProducto;
   }

}