package mupi.com.mortgageproject.loan;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class solicitud implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("codigoProducto")
   private String codigoProducto;

   @org.kie.api.definition.type.Label(value = "resultado")
   private java.lang.String resultado;

   public solicitud()
   {
   }

   public java.lang.String getCodigoProducto()
   {
      return this.codigoProducto;
   }

   public void setCodigoProducto(java.lang.String codigoProducto)
   {
      this.codigoProducto = codigoProducto;
   }

   public java.lang.String getResultado()
   {
      return this.resultado;
   }

   public void setResultado(java.lang.String resultado)
   {
      this.resultado = resultado;
   }

   public solicitud(java.lang.String codigoProducto, java.lang.String resultado)
   {
      this.codigoProducto = codigoProducto;
      this.resultado = resultado;
   }

}