package com.mupi.credito.reglas

rule "RGL001-1" //VALIDA APROBACION TASA
            lock-on-active true
            ruleflow-group "RGL2"
            
             when
           
            $p : Puntos(puntosPropuestos > 0, puntosPropuestos <= 1.5)
            
             then
             
            modify($p){
              setRequiereAprobacion("SI")
              
            }
            System.out.println("requiere aprobacion" + " " + $p.getRequiereAprobacion());
end

