package com.mupi.credito.reglas

rule "RGL001-1" //VALIDA APROBACION TASA
            lock-on-active true
            ruleflow-group "RGL2"
            
             when
           
            $p : Solicitud((codigoProducto == 36001 || (tipoGarantia == "SIN GARANTIA" && tipoPersona == "JURIDICA")))
            
             then
             
            modify($p){
              setRequiereGarantias("NO"),
              setRequiereGarantes("NO")
            }
            System.out.println("requiere gatantias" + " " + $p.getRequiereGarantias() + " " + "requiere garantes" + " " + $p.getRequiereGarantes());
end

