package com.mupi.credito.reglas

rule "RGl001-1" //VALLIDAR PORCENTAJE PATRIMONIO TECNICO
            lock-on-active true
            ruleflow-group "RGL1"
            
             when
           
            $p : PorcentajePTC(monto > (ptc * 0.06))
            
             then
             
            modify($p){
              setSuperaPorcentaje("SI")
            }
            System.out.println("supera porcentaje" + " " + $p.getSuperaPorcentaje());
end

rule "RGl001-2" //VALLIDAR PORCENTAJE PATRIMONIO TECNICO
            lock-on-active true
            ruleflow-group "RGL1"
            
             when
           
            $p : PorcentajePTC(monto <= (ptc * 0.06))
            
             then
             
            modify($p){
              setSuperaPorcentaje("NO")
            }
            System.out.println("supera porcentaje TEST2" + " " + $p.getSuperaPorcentaje());
end

