package com.mupi.credito.reglas

rule "RGS001-1/3" //REGLAS PARA DEFINIR CUANDO LA SOLICITUD REQUIERE GARANTES / GARANTIAS
            lock-on-active true
            ruleflow-group "RGS1"
            
             when
           
            $p : Solicitud((codigoProducto == 36001 || (tipoGarantia == "SIN GARANTIA" && tipoPersona == "JURIDICA")))
            
             then
            System.out.println("requiere gatantias" + " " + $p.getCodigoProducto() + " " + $p.getMontoSolicitado());
            modify($p){
              setRequiereGarantias("NO"),
              setRequiereGarantes("NO")
            }
            System.out.println("requiere gatantias" + " " + $p.getRequiereGarantias() + " " + "requiere garantes" + " " + $p.getRequiereGarantes());
end

rule "RGS001-2" //REGLAS PARA DEFINIR CUANDO LA SOLICITUD REQUIERE GARANTES / GARANTIAS
            lock-on-active true
            ruleflow-group "RGS1"
            
             when
            
            $p : Solicitud(grupoTipoCredito == "CONSUMO" && tipoGarantia == "QUIROGRAFARIO")
            
             then
            System.out.println("requiere gatantias" + " " + $p.getRequiereGarantias() +  "requiere garantes" + " " + $p.getRequiereGarantes());
            modify($p){
              setRequiereGarantias("NO"),
              setRequiereGarantes("SI")
            }
            System.out.println("requiere gatantias" + " " + $p.getRequiereGarantias() + " " + "requiere garantes" + " " + $p.getRequiereGarantes());
end

/*rule "RGS001-3"
            no-loop true
            ruleflow-group "RGS1"
            
             when
            
            $p : Solicitud(tipoGarantia == "SIN GARANTIA" && tipoPersona == "JURIDICA")
            
             then
            System.out.println("requiere gatantias" + " " + $p.getRequiereGarantias() +  "requiere garantes" + " " + $p.getRequiereGarantes());
            modify($p){
              setRequiereGarantias("NO"),
              setRequiereGarantes("NO")
            }
            System.out.println("requiere gatantias" + " " + $p.getRequiereGarantias() + " " + "requiere garantes" + " " + $p.getRequiereGarantes());
end*/

rule "RGS001-4" //REGLAS PARA DEFINIR CUANDO LA SOLICITUD REQUIERE GARANTES / GARANTIAS
            lock-on-active true
            ruleflow-group "RGS1"
            
             when
            
            $p : Solicitud(codigoProducto == null, (grupoTipoCredito == null || grupoTipoCredito == ""), 
            (tipoGarantia == null ||tipoGarantia == ""), (tipoCliente == null ||tipoCliente == ""), montoSolicitado == null, 
            (tipoPersona == null ||tipoPersona == ""))
            
             then
            System.out.println("requiere gatantias" + " " + $p.getRequiereGarantias() +  "requiere garantes" + " " + $p.getRequiereGarantes());
            modify($p){
              setRequiereGarantias("SI"),
              setRequiereGarantes("NO")
            }
            System.out.println("requiere gatantias" + " " + $p.getRequiereGarantias() + " " + "requiere garantes" + " " + $p.getRequiereGarantes());
end

rule "RGS002-1" //REGLAS PARA SETEAR EL VALOR FINAL DEL SCORE DE CREDITO
            lock-on-active true
            ruleflow-group "RGS1"
            
             when
           
            $p : Solicitud(grupoTipoCredito == "CONSUMO", tipoGarantia == "HIPOTECARIO",
            riesgoTotal <= 15000, estadoScoreSolicitud == "APROBADO")
            
             then
           
            modify($p){
                setResultadoScore("APROBADO")
            }
            System.out.println("resultado score" + " " + $p.getResultadoScore());
end

rule "RGS002-2" //REGLAS PARA SETEAR EL VALOR FINAL DEL SCORE DE CREDITO
            lock-on-active true
            ruleflow-group "RGS1"
            
             when
           
            $p : Solicitud((grupoTipoCredito == null || grupoTipoCredito == ""), 
            (tipoGarantia == null ||tipoGarantia == ""), (tipoCliente == null ||tipoCliente == ""), 
            montoSolicitado == null, riesgoTotal == null, estadoScoreSolicitud == "APROBADO")
            
             then
            modify($p){
                setResultadoScore("ANALISIS")
            }
            System.out.println("resultado score" + " " + $p.getResultadoScore());
end

rule "RGS002-3" //REGLAS PARA SETEAR EL VALOR FINAL DEL SCORE DE CREDITO
            lock-on-active true
            ruleflow-group "RGS1"
            
             when
           
            $p : Solicitud(estadoScoreSolicitud == "ANALISIS")
            
             then
            modify($p){
                setResultadoScore("ANALISIS")
            }
            System.out.println("resultado score" + " " + $p.getResultadoScore());
end
rule "RGS002-4" //REGLAS PARA SETEAR EL VALOR FINAL DEL SCORE DE CREDITO
            lock-on-active true
            ruleflow-group "RGS1"
            
             when
           
            $p : Solicitud(estadoScoreSolicitud == "NEGADO")
        
             then
            modify($p){
                setResultadoScore("NEGADO")
            }
            System.out.println("resultado score" + " " + $p.getResultadoScore());
end

rule "RGS002-5" //REGLAS PARA SETEAR EL VALOR FINAL DEL SCORE DE CREDITO
            lock-on-active true
            ruleflow-group "RGS1"
            
             when
           
            $p : Solicitud((grupoTipoCredito == null || grupoTipoCredito == ""), 
            (tipoGarantia == null ||tipoGarantia == ""), (tipoCliente == null ||tipoCliente == ""), montoSolicitado == null, 
            (estadoScoreSolicitud == null ||estadoScoreSolicitud == ""))
        
             then
            modify($p){
                setResultadoScore("ANALISIS")
            }
            System.out.println("resultado score" + " " + $p.getResultadoScore());
end

rule "RGS003-1" //REGLAS PARA SELECCIONAR EL FUNCIONARIO QUE GESTIONA LA SOLICITUD DE CREDITO
            lock-on-active true
            ruleflow-group "RGS1"
            
             when
           
            $p : Solicitud(agencia != "39", agencia != "", agencia != null, ratificada == null)
        
             then
            modify($p){
                setConsultaDatosSolicitud("operadorOficialCliente")
            }
            System.out.println("resultado consultaDatosSolicitud" + " " + $p.getConsultaDatosSolicitud());
end

rule "RGS003-2" //REGLAS PARA SELECCIONAR EL FUNCIONARIO QUE GESTIONA LA SOLICITUD DE CREDITO
            lock-on-active true
            ruleflow-group "RGS1"
            
             when
           
            $p : Solicitud(agencia == "39", ratificada != 1, ratificada != null)
        
             then
            modify($p){
                setConsultaDatosSolicitud("operadorCreoSolicitud")
            }
            System.out.println("resultado consultaDatosSolicitud" + " " + $p.getConsultaDatosSolicitud());
end

rule "RGS003-3" //REGLAS PARA SELECCIONAR EL FUNCIONARIO QUE GESTIONA LA SOLICITUD DE CREDITO
            lock-on-active true
            ruleflow-group "RGS1"
            
             when
           
            $p : Solicitud(agencia == "39", ratificada == 1)
        
             then
            modify($p){
                setConsultaDatosSolicitud("operadorOficialCliente")
            }
            System.out.println("resultado consultaDatosSolicitud" + " " + $p.getConsultaDatosSolicitud());
end

rule "RGS004-1" //REGLAS PARA SETERAR EL NIVEL Y ORDEN  DE LA SOLICITUD
            lock-on-active true
            ruleflow-group "RGS1"
            
             when
           
            $p : Solicitud(codigoOficialCuenta == 200)
        
             then
            modify($p){
                setNivelActual(18),
                setOrdenComite(0)
            }
            System.out.println("resultado nivelActual" + " " + $p.getNivelActual() + " " + "resultado ordenComite" + " " + $p.getOrdenComite());
end

rule "RGS004-2" //REGLAS PARA SETERAR EL NIVEL Y ORDEN  DE LA SOLICITUD
            lock-on-active true
            ruleflow-group "RGS1"
            
             when
           
            $p : Solicitud(codigoOficialCuenta == null, codigoProducto == null,  
            (nombreProducto == null ||nombreProducto == ""), (grupoTipoCredito == null ||grupoTipoCredito == ""), 
            (tipoGarantia == null ||tipoGarantia == ""),(tipoCliente == null ||tipoCliente == ""), 
            (tipoPersona == null ||tipoPersona == ""), montoSolicitado == null)
        
             then
            modify($p){
                setNivelActual(1),
                setOrdenComite(0)
            }
            System.out.println("resultado nivelActual" + " " + $p.getNivelActual() + " " + "resultado ordenComite" + " " + $p.getOrdenComite());
end

rule "RGS005-1" //REGLAS PARA SETERAR EL NIVEL Y ORDEN  DE LA SOLICITUD
            lock-on-active true
            ruleflow-group "RGS1"
            
             when
           
            $p : Solicitud(ratificada == 0, ratificadaExt == "SI")
        
             then
            modify($p){
                setSolicitudRatificadaAprobada(1)
            }
            System.out.println("resultado solicitudRatificadaAprobada" + " " + $p.getSolicitudRatificadaAprobada());
end
