package com.mupi.credito.reglas;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PorcentajePTC implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public PorcentajePTC() {
    }

}