package com.mupi.credito.reglas;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Puntos implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.math.BigDecimal puntosPropuestos;

   public Puntos()
   {
   }

   public java.math.BigDecimal getPuntosPropuestos()
   {
      return this.puntosPropuestos;
   }

   public void setPuntosPropuestos(java.math.BigDecimal puntosPropuestos)
   {
      this.puntosPropuestos = puntosPropuestos;
   }

   public Puntos(java.math.BigDecimal puntosPropuestos)
   {
      this.puntosPropuestos = puntosPropuestos;
   }

}