package mupi.com.mortgageproject.loan;

rule "RGS001-1/3" //REGLAS PARA DEFINIR CUANDO LA SOLICITUD REQUIERE GARANTES / GARANTIAS
            lock-on-active true
            ruleflow-group "RGS1"
            
             when
           
            $p : Solicitud((codigoProducto == 36001 || (tipoGarantia == "SIN GARANTIA" && tipoPersona == "JURIDICA")))
            
             then
            System.out.println("requiere gatantias" + " " + $p.getCodigoProducto() + " " + $p.getMontoSolicitado());
            modify($p){
              setRequiereGarantias("NO"),
              setRequiereGarantes("NO")
            }
            System.out.println("requiere gatantias" + " " + $p.getRequiereGarantias() + " " + "requiere garantes" + " " + $p.getRequiereGarantes());
end

rule "RGS001-2" //REGLAS PARA DEFINIR CUANDO LA SOLICITUD REQUIERE GARANTES / GARANTIAS
            lock-on-active true
            ruleflow-group "RGS1"
            
             when
            
            $p : Solicitud(grupoTipoCredito == "CONSUMO" && tipoGarantia == "QUIROGRAFARIO")
            
             then
            System.out.println("requiere gatantias" + " " + $p.getRequiereGarantias() +  "requiere garantes" + " " + $p.getRequiereGarantes());
            modify($p){
              setRequiereGarantias("NO"),
              setRequiereGarantes("SI")
            }
            System.out.println("requiere gatantias" + " " + $p.getRequiereGarantias() + " " + "requiere garantes" + " " + $p.getRequiereGarantes());
end

/*rule "RGS001-3"
            no-loop true
            ruleflow-group "RGS1"
            
             when
            
            $p : Solicitud(tipoGarantia == "SIN GARANTIA" && tipoPersona == "JURIDICA")
            
             then
            System.out.println("requiere gatantias" + " " + $p.getRequiereGarantias() +  "requiere garantes" + " " + $p.getRequiereGarantes());
            modify($p){
              setRequiereGarantias("NO"),
              setRequiereGarantes("NO")
            }
            System.out.println("requiere gatantias" + " " + $p.getRequiereGarantias() + " " + "requiere garantes" + " " + $p.getRequiereGarantes());
end*/

rule "RGS001-4" //REGLAS PARA DEFINIR CUANDO LA SOLICITUD REQUIERE GARANTES / GARANTIAS
            lock-on-active true
            ruleflow-group "RGS1"
            
             when
            // 
            //montoSolicitado == null, tipoPersona == null
            $p : Solicitud(codigoProducto == null, (grupoTipoCredito == null || grupoTipoCredito == ""), 
            (tipoGarantia == null ||tipoGarantia == ""), (tipoCliente == null ||tipoCliente == ""), montoSolicitado == null, 
            (tipoPersona == null ||tipoPersona == ""))
            
             then
            System.out.println("requiere gatantias" + " " + $p.getRequiereGarantias() +  "requiere garantes" + " " + $p.getRequiereGarantes());
            modify($p){
              setRequiereGarantias("SI"),
              setRequiereGarantes("NO")
            }
            System.out.println("requiere gatantias" + " " + $p.getRequiereGarantias() + " " + "requiere garantes" + " " + $p.getRequiereGarantes());
end

rule "RGS002-1" //REGLAS PARA SETEAR EL VALOR FINAL DEL SCORE DE CREDITO
            lock-on-active true
            ruleflow-group "RGS1"
            
             when
           
            $p : Solicitud(grupoTipoCredito == "CONSUMO", tipoGarantia == "HIPOTECARIO",
            montoSolicitado <= 15000, estadoScoreSolicitud == "APROBADO")
            
             then
            System.out.println("requiere gatantias" + " " + $p.getCodigoProducto() + " " + $p.getMontoSolicitado());
            modify($p){
                setResultadoScore("APROBADO")
            }
            System.out.println("resultado score" + " " + $p.getResultadoScore());
end

rule "RGS002-2" //REGLAS PARA SETEAR EL VALOR FINAL DEL SCORE DE CREDITO
            lock-on-active true
            ruleflow-group "RGS1"
            
             when
           
            $p : Solicitud(estadoScoreSolicitado == "APROBADO")
            
             then
            modify($p){
                setResultadoScore("ANALISIS")
            }
            System.out.println("resultado score" + " " + $p.getResultadoScore());
end

rule "RGS002-3" //REGLAS PARA SETEAR EL VALOR FINAL DEL SCORE DE CREDITO
            lock-on-active true
            ruleflow-group "RGS1"
            
             when
           
            $p : Solicitud(estadoScoreSolicitado == "ANALISIS")
            
             then
            modify($p){
                setResultadoScore("ANALISIS")
            }
            System.out.println("resultado score" + " " + $p.getResultadoScore());
end
rule "RGS002-4" //REGLAS PARA SETEAR EL VALOR FINAL DEL SCORE DE CREDITO
            lock-on-active true
            ruleflow-group "RGS1"
            
             when
           
            $p : Solicitud(estadoScoreSolicitado == "NEGADO")
        
             then
            modify($p){
                setResultadoScore("NEGADO")
            }
            System.out.println("resultado score" + " " + $p.getResultadoScore());
end

rule "RGS002-5" //REGLAS PARA SETEAR EL VALOR FINAL DEL SCORE DE CREDITO
            lock-on-active true
            ruleflow-group "RGS1"
            
             when
           
            $p : Solicitud((grupoTipoCredito == null || grupoTipoCredito == ""), 
            (tipoGarantia == null ||tipoGarantia == ""), (tipoCliente == null ||tipoCliente == ""), montoSolicitado == null, 
            (estadoScoreSolicitado == null ||estadoScoreSolicitado == ""))
        
             then
            modify($p){
                setResultadoScore("NEGADO")
            }
            System.out.println("resultado score" + " " + $p.getResultadoScore());
end
