package mupi.com.mortgageproject.loan;

rule "RGS002-1"
            no-loop true
            ruleflow-group "RGS2"
            
             when
           
            $p : Solicitud(grupoTipoCredito == "CONSUMO", tipoGarantia == "HIPOTECARIO",
            montoSolicitado <= 15000, estadoScoreSolicitado == "APROBADO")
            
             then
            System.out.println("requiere gatantias" + " " + $p.getCodigoProducto() + " " + $p.getMontoSolicitado());
            modify($p){
                setResultadoScore("APROBADO")
            }
            System.out.println("resultado score" + " " + $p.getResultadoScore() + " " + "requiere garantes" + " " + $p.getRequiereGarantes());
end