package mupi.com.mortgageproject.loan;

rule "RGS1-1"
            no-loop true
            ruleflow-group "REGLA"
            
             when
            eval(true)
            //$p : Solicitud(codigoProducto == 36001)
            
             then
            //System.out.println("requiere gatantias" + " " + $p.getCodigoProducto() + " " + $p.getMontoSolicitado());
            //modify($p){
              //setRequiereGarantias("NO"),
              //setRequiereGarantes("NO")
            //}
            System.out.println("requiere gatantias");
end