package mupi.com.mortgageproject.loan;

rule "RGS1-1"
            no-loop true
            ruleflow-group "RGS1"
            
             when
           
            $p : Solicitud(codigoProducto == 36001)
            
             then
            System.out.println("requiere gatantias" + " " + $p.getCodigoProducto() + " " + $p.getMontoSolicitado());
            modify($p){
              setRequiereGarantias("NO"),
              setRequiereGarantes("NO")
            }
            System.out.println("requiere gatantias" + " " + $p.getRequiereGarantias() + " " + "requiere garantes" + " " + $p.getRequiereGarantes());
end