//import org.drools.runtime.process.WorkflowProcessInstance
package mupi.com.mortgageproject.loan;
//package mupi.com.mortgageproject.loan.solicitud


rule "RGS001"
            ruleflow-group "RGS1"
             when
              //(codigoProducto2.equals(codigoProducto))
             //(codigoProducto.equals("36001")
             //$resultado : "NO"
             //$codigoProducto : "123" 
             //$process:WorkflowProcessInstance()
             eval(true)
             System.out.println("requiere gatantias"+ " "+ _codigoProducto);
             then
             System.out.println("requiere gatantias"+ " ");
end
