//import org.drools.runtime.process.WorkflowProcessInstance
package mupi.com.mortgageproject.loan
import mupi.com.mortgageproject.loan.solicitud;


rule "RGS001-1"
            no-loop true
            ruleflow-group "RGS1"
            
             when
              //(codigoProducto2.equals(codigoProducto))
             //(codigoProducto.equals("36001")
             //$resultado : "NO"
             //$codigoProducto : "123" 
             //$process:WorkflowProcessInstance()
             //$p : codigoProducto == "36001" 
            // eval(true)
           
            $p : solicitud(codigoProducto == "123")
            
             then
            System.out.println("requiere gatantias" + " " + $p.getCodigoProducto() +  " " + $p.getResultado());
            modify($p){
              setRequiereGarantia("NO")
              setRequiereGarantes("SI");
            }
            System.out.println("requiere gatantias" + " " + $p.getRequiereGarantias() +  "requiere garantes" + "" + $p.getRequiereGarantes());
end

rule "RGS001-2"
            no-loop true
            ruleflow-group "RGS1"
            
             when
            
            $p : solicitud(grupoTipoCredito == "CONSUMO" && tipoGarantia == "QUIROGRAFARIO")
            
             then
            System.out.println("requiere gatantias" + " " + $p.getRequiereGarantias() +  "requiere garantes" + "" + $p.getRequiereGarantes());
            modify($p){
              setRequiereGarantia("NO")
              //setRequiereGarantes("SI");
            }
            System.out.println("requiere gatantias" + " " + $p.getRequiereGarantias() +  "requiere garantes" + "" + $p.getRequiereGarantes());
end

