//package mupi.com.mortgageproject.loan;
//import org.drools.runtime.process.WorkflowProcessInstance
package mupi.com.mortgageproject.loan
import mupi.com.mortgageproject.loan.Solicitud


rule "RGS001-1"
            no-loop true
            ruleflow-group "RGS1"
            
             when
           
            $p : Solicitud(codigoProducto == 36001)
            
             then
            System.out.println("requiere gatantias" + " " + $p.getCodigoProducto() + " " + $p.getMontoSolicitado());
            modify($p){
              setRequiereGarantias("NO"),
              setRequiereGarantes("NO")
            }
            System.out.println("requiere gatantias" + " " + $p.getRequiereGarantias() + " " + "requiere garantes" + " " + $p.getRequiereGarantes());
end

rule "RGS001-2"
            no-loop true
            ruleflow-group "RGS1"
            
             when
            
            $p : Solicitud(grupoTipoCredito == "CONSUMO" && tipoGarantia == "QUIROGRAFARIO")
            
             then
            System.out.println("requiere gatantias" + " " + $p.getRequiereGarantias() +  "requiere garantes" + " " + $p.getRequiereGarantes());
            modify($p){
              setRequiereGarantias("NO"),
              setRequiereGarantes("SI")
            }
            System.out.println("requiere gatantias" + " " + $p.getRequiereGarantias() + " " + "requiere garantes" + " " + $p.getRequiereGarantes());
end

rule "RGS001-3"
            no-loop true
            ruleflow-group "RGS1"
            
             when
            
            $p : Solicitud(tipoGarantia == "SIN GARANTIA" && tipoPersona == "JURIDICA")
            
             then
            System.out.println("requiere gatantias" + " " + $p.getRequiereGarantias() +  "requiere garantes" + " " + $p.getRequiereGarantes());
            modify($p){
              setRequiereGarantias("NO"),
              setRequiereGarantes("NO")
            }
            System.out.println("requiere gatantias" + " " + $p.getRequiereGarantias() + " " + "requiere garantes" + " " + $p.getRequiereGarantes());
end

rule "RGS001-4"
            no-loop true
            ruleflow-group "RGS1"
            
             when
            // 
            //montoSolicitado == null, tipoPersona == null
            $p : Solicitud(codigoProducto == null, (grupoTipoCredito == "" ||grupoTipoCredito == null) , tipoGarantia == "", tipoCliente == "", montoSolicitado == null, tipoPersona == "")
            
             then
            System.out.println("requiere gatantias" + " " + $p.getRequiereGarantias() +  "requiere garantes" + " " + $p.getRequiereGarantes());
            modify($p){
              setRequiereGarantias("SI"),
              setRequiereGarantes("NO")
            }
            System.out.println("requiere gatantias" + " " + $p.getRequiereGarantias() + " " + "requiere garantes" + " " + $p.getRequiereGarantes());
end


